---
- name : win_chocolatey module demo
  hosts: win
  become: false
  gather_facts: false
  vars:
   - packages:
     - sql-server-express
     
  tasks:
  - name : install packages
    chocolatey.chocolatey.win_chocolatey:
      name: "{{ packages }}"
      state: present

