---
- name : win_chocolatey module demo
  hosts: win
  become: false
  gather_facts: false
  vars:
   - packages:
     - git

  tasks:
  - name : install packages
    chocolatey.chocolatey.win_chocolatey:
      name: "{{ packages }}"
      state: absent

