---
- name: WindowsService
  hosts: win

  tasks:
    - name: This will be installed the SQL Service Windows Service in Auto mode
      win_command: C:\SQL2017\setup.exe /q /ACTION=Install /FEATURES=SQL /INSTANCENAME=MSSQLSERVER /SQLSVCACCOUNT="mtadmin" /SQLSVCPASSWORD="1q2w3eASD@1310" /SQLSYSADMINACCOUNTS="mtadmin" /AGTSVCACCOUNT="NT AUTHORITY\NETWORK SERVICE" /SQLSVCINSTANTFILEINIT="True" /IACCEPTSQLSERVERLICENSETERMS
      args:
        chdir: C:\SQL2017
        #executable: cmd
      register: result
      ignore_errors: yes
    - name: Display output
      debug:
        var: result.stdout_lines

        
        