all:
  hosts:
    windowsdc:
      ansible_host: 192.168.106.132
      ansible_user: Administrator
      ansible_password: 1q2w3eASD
      ansible_connection: winrm
      ansible_winrm_transport: basic
      ansible_winrm_server_cert_validation: ignore
