---
- name: Promote Windows Server to Domain Controller
  hosts: windowsdc
  gather_facts: no
  collections:
    - ansible.windows
    - community.windows

  tasks:
    - name: Install AD Domain Services
      ansible.windows.win_feature:
        name: AD-Domain-Services
        include_management_tools: yes
        state: present

    - name: Promote to Domain Controller and create new forest
      microsoft.ad.domain:
        dns_domain_name: "{{ domain_name }}"
        domain_netbios_name: "{{ netbios_name }}"
        safe_mode_password: "{{ windows_admin_password }}"
        install_dns: yes
        reboot: yes
