---
- name: Promote Windows Server to Domain Controller
  hosts: windowsdc
  collections:
    - ansible.windows
  gather_facts: no

  vars:
    domain_name: mttest.local
    netbios_name: MTTEST
    new_hostname: dc01
    # ❌ removed 'safe_mode_password' from here to avoid early reference issues

  tasks:

    - name: DEBUG — confirm password is visible at runtime
      ansible.builtin.debug:
        msg: "Admin password is {{ windows_admin_password }}"

    - name: Rename computer to dc01
      ansible.windows.win_hostname:
        name: "{{ new_hostname }}"
      register: rename_result

    - name: Reboot after rename if needed
      ansible.windows.win_reboot:
        msg: "Rebooting after hostname change"
        timeout: 600
      when: rename_result.reboot_required

    - name: Install AD-Domain-Services feature
      ansible.windows.win_feature:
        name: AD-Domain-Services
        include_management_tools: yes
        state: present

    - name: Promote to domain controller and create new forest
      ansible.windows.win_domain:
        dns_domain_name: "{{ domain_name }}"
        domain_netbios_name: "{{ netbios_name }}"
        safe_mode_password: "{{ windows_admin_password }}"
        install_dns: yes
        reboot: yes
